default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_management_app_development

test:
  <<: *default
  database: project_management_app_test

production:
  primary: &primary_production
    <<: *default
    database: project_management_app_production
    username: postgres
    password: postgres
  cache:
    <<: *primary_production
    database: project_management_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: project_management_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: project_management_app_production_cable
    migrations_paths: db/cable_migrate
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_management_app_development

test:
  <<: *default
  database: project_management_app_test

production:
  primary: &primary_production
    <<: *default
    database: project_management_app_production
    username: postgres
    password: postgres
  cache:
    <<: *primary_production
    database: project_management_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: project_management_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: project_management_app_production_cable
    migrations_paths: db/cable_migrate
